before_deploy: "echo 'ready?'"
branches:
  only:
    - main
deploy:
  provider: firebase
  token:
    secure: "Ao3tXvLr05CCOskeQyw2liRi9VCpcvNvzSItxrEbIexrDJGok22GuCyBGesoOF/eiUeVroPlGcgeovQ4afTcb6oDKG4hB6Lvcu80NxRSWeop7zclIiWVSF4GvZoP3fjT5P2vzQGkSGWvTwl+J4HTsSfT/jmQxcRTzwc/37oHtEtDKu8SGmUNB0LEhufIj4/IZYHGbmkH5vM4T5dm1WDDFTYDAG9+ao2/ZAfG8+ReyESMNufWPVcbeVVLVV7IvzznuRFxQhVkaljUOAGCjf1h1+SqqzzAGY4ey0dSe1MEol4JvjlgOOUJO+TsJfV9GgoMfnenAK1br+sjl8pEtjupLZ92qqwEnPATFKZDsa6UXLSLjTERl+0oQRG2xXfoJb+wYXBn4437Uzk+Rtr2YUqSKRRBjsH3OuEZGAeq9QzM/ptUO7Hg+7UtfbwvVXNYfohZLf/RVqyEDmo9syLAJGhIwSw6+LyuCSfi2YViVDdV2dvKMAbBQm4WbCrBSOKykIH5LmpcxtNhBHFpvJzAa+oJJxHgEl/zet5XHMG+wW00aTsAKfZfP5ux7eHsrGkZLG+xNO+VcCLyudrR9n2C3gq9hNtqzJ/UuY50/1+m8BO1yqZh21UWI2mEIAnpQuNnMJsB3mqHSxTvaEFxj3goRXcZ/F7BRSkj3V4aZciN6LQ5EUg="
  on:
    branch: main
