before_deploy: "echo 'ready?'"
branches:
  only:
    - main
deploy:
  provider: firebase
  token:
    secure: "1//0cXiUJxwY0WNZCgYIARAAGAwSNwF-L9IrFccRvRgivstE8GVFJiqSD6NIpU2gjkjenGgsropg3z37mE8j0HLWgG6N8eTlwPF9P4Q"
  on:
    branch: main
